
package Ejercicio5;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public class Ventana extends javax.swing.JFrame {
    private Timer tiempo;
    private int centesimasSegundo = 0, segundos = 0, minutos = 0, horas = 0;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimasSegundo++;
            if(centesimasSegundo == 100){
                segundos++;
                centesimasSegundo = 0;
            }
            if(segundos == 60){
                minutos++;
                segundos = 0;
            }
            if(minutos == 60){
                horas++;
                minutos = 0;
            }
            actualizarEtiquetaTiempo();
        }
    };
    
    private void actualizarEtiquetaTiempo(){
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimasSegundo<=9?"0":"")+centesimasSegundo;
        etiquetaTiempo.setText(texto);
    }
    
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenCronometro = new javax.swing.JLabel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronómetro");
        setResizable(false);

        panel.setLayout(null);

        imagenCronometro.setBackground(new java.awt.Color(0, 0, 0));
        imagenCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cronometro.png"))); // NOI18N
        imagenCronometro.setText("jLabel1");
        panel.add(imagenCronometro);
        imagenCronometro.setBounds(10, 40, 154, 154);

        etiquetaCronometro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        etiquetaCronometro.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCronometro.setText("Cronómetro");
        panel.add(etiquetaCronometro);
        etiquetaCronometro.setBounds(250, 30, 200, 30);

        etiquetaTiempo.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTiempo.setText("00:00:00:00");
        panel.add(etiquetaTiempo);
        etiquetaTiempo.setBounds(240, 90, 230, 40);

        botonIniciar.setBackground(new java.awt.Color(51, 204, 255));
        botonIniciar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar);
        botonIniciar.setBounds(210, 150, 90, 40);

        botonPausar.setBackground(new java.awt.Color(0, 204, 255));
        botonPausar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar);
        botonPausar.setBounds(310, 150, 90, 40);

        botonDetener.setBackground(new java.awt.Color(0, 204, 255));
        botonDetener.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener);
        botonDetener.setBounds(410, 150, 90, 40);

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrera.jpg"))); // NOI18N
        panel.add(etiquetaFondo);
        etiquetaFondo.setBounds(0, 0, 536, 217);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setEnabled(false);
        botonIniciar.setText("Reanudar");
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        tiempo.stop();
        botonIniciar.setEnabled(true);
        botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }
        botonIniciar.setText("Iniciar");
        botonDetener.setEnabled(false);
        botonPausar.setEnabled(false);
        
        horas = 0;
        minutos = 0;
        segundos = 0;
        centesimasSegundo = 0;
        
        actualizarEtiquetaTiempo();
    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel imagenCronometro;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
