
package Ejercicio6;

import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {
    private Usuario usuario1 = new Usuario("Tino2525", "25mayo2002MMO");
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void iniciarSesión(){
        String nombre = cajaNombre.getText();
        
         if(nombre.equals(usuario1.getNombreUsuario())){
            String contraseña = "";
            
            for (int i = 0; i < cajaContraseña.getPassword().length; i++) {
                contraseña += cajaContraseña.getPassword()[i];
            }
            if(contraseña.equals(usuario1.getContraseñaUsuario())){
                JOptionPane.showMessageDialog(null, "Ingresaste al sistema");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error, contraseña incorrecta");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error, usuario desconocido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        etiquetaLogo = new javax.swing.JLabel();
        etiquetaUsuario = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        etiquetaContraseña = new javax.swing.JLabel();
        cajaContraseña = new javax.swing.JPasswordField();
        botonIniciarSesión = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.setMinimumSize(new java.awt.Dimension(512, 640));
        panel.setPreferredSize(new java.awt.Dimension(512, 640));
        panel.setLayout(null);

        botonSalir.setBackground(new java.awt.Color(39, 102, 144));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panel.add(botonSalir);
        botonSalir.setBounds(440, 10, 61, 30);

        etiquetaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        etiquetaLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel.add(etiquetaLogo);
        etiquetaLogo.setBounds(170, 130, 180, 190);

        etiquetaUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaUsuario.setText("Usuario:");
        panel.add(etiquetaUsuario);
        etiquetaUsuario.setBounds(150, 400, 70, 20);

        cajaNombre.setBackground(new java.awt.Color(56, 131, 204));
        cajaNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panel.add(cajaNombre);
        cajaNombre.setBounds(150, 420, 230, 30);

        etiquetaContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaContraseña.setText("Contraseña:");
        panel.add(etiquetaContraseña);
        etiquetaContraseña.setBounds(150, 470, 90, 20);

        cajaContraseña.setBackground(new java.awt.Color(125, 57, 203));
        cajaContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cajaContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaContraseñaKeyTyped(evt);
            }
        });
        panel.add(cajaContraseña);
        cajaContraseña.setBounds(150, 492, 230, 30);

        botonIniciarSesión.setBackground(new java.awt.Color(39, 102, 144));
        botonIniciarSesión.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonIniciarSesión.setText("Iniciar Sesión");
        botonIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesiónActionPerformed(evt);
            }
        });
        panel.add(botonIniciarSesión);
        botonIniciarSesión.setBounds(330, 565, 140, 40);

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        panel.add(etiquetaFondo);
        etiquetaFondo.setBounds(0, 0, 512, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesiónActionPerformed

        String nombre = cajaNombre.getText();
        
        if(nombre.equals(usuario1.getNombreUsuario())){
            String contraseña = "";
            
            for (int i = 0; i < cajaContraseña.getPassword().length; i++) {
                contraseña += cajaContraseña.getPassword()[i];
            }
            if(contraseña.equals(usuario1.getContraseñaUsuario())){
                JOptionPane.showMessageDialog(null, "Ingresaste al sistema");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error, contraseña incorrecta");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error, usuario desconocido");
        } 
    }//GEN-LAST:event_botonIniciarSesiónActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void cajaContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaContraseñaKeyTyped
        if(evt.getKeyChar() == '\n'){
            iniciarSesión();
        }
        
        
    }//GEN-LAST:event_cajaContraseñaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesión;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPasswordField cajaContraseña;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaLogo;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
